version: "3.9"
services:
  python-app: 
    image: python:latest 
    build:
      context: . 
      dockerfile: Dockerfile
    container_name: python-app
    ports:
      - "8000:8000" 
    volumes:
      - /tmp/app_data:/app/app/data
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]
